name: Test workflow (Short)

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov=farmgym --cov-report xml  tests/
      - name: Coverage
        uses: codecov/codecov-action@v3

  ruff:
    name: Check formatting/Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
